apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: customerservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: acmeair-customerservice
  minReplicas: 1
  maxReplicas: 15
  metrics:
  - type: Pods
    pods:
      metric:
        name: query_per_second_customerservice
      target:
        type: AverageValue
        averageValue: "100"
