apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flightservice
spec:
  endpoints:
  - targetPort: 9080
    path: /prometheus
  selector:
    matchLabels:
      app: flightservice
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bookingservice
spec:
  endpoints:
  - targetPort: 9080
    path: /prometheus
  selector:
    matchLabels:
      app: bookingservice
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: customerservice
spec:
  endpoints:
  - targetPort: 9080
    path: /prometheus
  selector:
    matchLabels:
      app: customerservice