apiVersion: chpa.my.domain/v1
kind: CHPA
metadata:
  name: chpa-sample
spec:
  scaleTargets:
  - scaleTargetRef:
      name: acmeair-flightservice
    metric:
      name: query_per_second_flightservice
      targetValue: 10
    weight: 1
  - scaleTargetRef:
      name: acmeair-bookingservice
    metric:
      name: query_per_second_bookingservice
      targetValue: 10
    weight: 1
  - scaleTargetRef:
      name: acmeair-customerservice
    metric:
      name: query_per_second_customerservice
      targetValue: 10
    weight: 1