apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chpa-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chpa-manager-role
subjects:
- kind: ServiceAccount
  name: chpa-controller-manager
  namespace: kube-system
